nome=str(input('Digite seu nome completo: ')).strip()
ma=nome.upper()
mi=nome.lower()
r=nome.split()
t=len(nome)-nome.count(' ')
p=nome.find(' ')
primeiro= nome.split()
print('Seu nome em letras maíusculas fica {}'.format(ma))
print('Seu nome em letras minúsculas fica {}'.format(mi))
print('Seu nome tem {} caracteres'.format(t))
print('Seu primeiro nome tem {} letras'.format(p))
print('Seu primeiro nome é {} e tem {} letras.'.format(primeiro[0], len(primeiro[0])))